import {
  collection,
  doc,
  getDocs,
  setDoc,
  updateDoc,
  query,
  orderBy,
  onSnapshot,
} from 'firebase/firestore';
import { db } from '../firebase/config';
import {
  Contact,
  Lead,
  Conversation,
  Message,
  EmailThread,
  KnowledgeDocument,
  OutboundCampaign,
  OutboundProspect,
  LeadActivity,
  SystemSettings,
  Channel,
} from '../types';
import { INITIAL_KNOWLEDGE_DOCUMENTS } from './knowledgeData';

// Default initial system settings
export const DEFAULT_SETTINGS: SystemSettings = {
  channelModes: {
    WHATSAPP: 'AUTO',
    EMAIL: 'AUTO',
    INSTAGRAM: 'AUTO',
    FACEBOOK: 'AUTO',
    LINKEDIN: 'REVIEW',
    WEBSITE: 'AUTO',
  },
  sendingAccounts: [
    { id: 'acc-1', email: 'sales@umrah360.in', name: 'Umrah360 Sales', isDefault: true },
    { id: 'acc-2', email: 'hello@umrah360.in', name: 'Umrah360 Concierge', isDefault: false },
    { id: 'acc-3', email: 'amaavigo@gmail.com', name: 'Umrah360 Automation', isDefault: false },
  ],
  emailSignature: 'Regards,\nUmrah360 Outbound Growth Team\nwww.umrah360.in',
  debounceSeconds: 3,
  apolloApiKeyConfigured: true,
  webhookEndpoint: 'https://api.umrah360.in/v1/webhooks',
  updatedAt: new Date().toISOString(),
};

// Initial Indian Umrah Operators Campaign (Section 7, Section 72)
export const INITIAL_CAMPAIGN: OutboundCampaign = {
  campaignId: 'camp-indian-umrah-operators',
  name: 'Indian Umrah Operators 2026',
  description: 'Outbound campaign targeting Founders & Directors of pilgrimage agencies in India',
  targetIndustry: 'Pilgrimage, Hajj & Umrah, Leisure Travel',
  targetLocation: 'India (Delhi NCR, Mumbai, Hyderabad, Bangalore, Lucknow)',
  targetJobTitles: ['Founder', 'Owner', 'Managing Director', 'CEO', 'Director'],
  targetCompanySize: '1-50 employees',
  apolloSearchConfiguration: {
    q_organization_keyword_tags: ['umrah', 'hajj', 'pilgrimage', 'travel agency'],
    person_titles: ['Founder', 'Owner', 'Managing Director', 'Director'],
    person_locations: ['India'],
    organization_num_employees_ranges: ['1,10', '11,20', '21,50'],
  },
  emailAccountId: 'acc-1',
  emailSubjectTemplate: 'Umrah360 for {{companyName}} - Automate B2B Packages & Visa Operations',
  emailBodyTemplate: `Hi {{firstName}},\n\nI noticed you are leading operations at {{companyName}}. We work with top Umrah operators across India to automate their dynamic package costing, Makkah/Madinah room allocations, and sub-agent B2B voucher distribution.\n\nMost operators we speak with were spending 15+ hours weekly updating manual spreadsheets and WhatsApp groups for agent pricing. Umrah360 gives your agency an automated B2B portal with live supplier costs and compliant invoicing.\n\nWould you be open to exploring how this could streamline your upcoming season?\n\nRegards,\nUmrah360 Growth Team`,
  status: 'RUNNING',
  stats: {
    prospectsFound: 48,
    prospectsQualified: 42,
    emailsSent: 35,
    replies: 14,
    engaged: 11,
    qualifiedLeads: 9,
    meetingsRequested: 5,
    unsubscribes: 1,
    bounces: 0,
  },
  createdAt: '2026-09-10T08:00:00Z',
  updatedAt: '2026-09-15T10:00:00Z',
};

// Initial Apollo Prospects including Rahul Sharma (Section 72)
export const INITIAL_PROSPECTS: OutboundProspect[] = [
  {
    prospectId: 'prospect-rahul-sharma',
    campaignId: 'camp-indian-umrah-operators',
    apolloPersonId: 'ap_person_9847120',
    apolloOrganizationId: 'ap_org_38194',
    firstName: 'Rahul',
    lastName: 'Sharma',
    email: 'rahul@abctravels.in',
    phone: '+91 98100 23456',
    jobTitle: 'Founder & Managing Director',
    companyName: 'ABC Travels',
    industry: 'Pilgrimage & Leisure Tours',
    companySize: '11-50 employees',
    location: 'New Delhi, India',
    website: 'https://abctravels.in',
    linkedinUrl: 'https://linkedin.com/in/rahulsharma-abc',
    source: 'APOLLO',
    status: 'ENGAGED',
    qualificationStatus: 'QUALIFIED',
    qualificationScore: 92,
    qualificationReason: 'High-intent founder at prominent Delhi Umrah agency with active B2B sub-agent network.',
    emailThreadId: 'thread-rahul-sharma',
    conversationId: 'conv-rahul-sharma',
    createdAt: '2026-09-12T09:00:00Z',
    updatedAt: '2026-09-15T11:20:00Z',
  },
  {
    prospectId: 'prospect-tariq-khan',
    campaignId: 'camp-indian-umrah-operators',
    apolloPersonId: 'ap_person_5102941',
    firstName: 'Tariq',
    lastName: 'Khan',
    email: 'tariq@albarakatours.com',
    phone: '+91 98450 11223',
    jobTitle: 'Director of Operations',
    companyName: 'Al Baraka Tours & Travels',
    industry: 'Hajj & Umrah Tour Operator',
    companySize: '15-25 employees',
    location: 'Mumbai, India',
    source: 'APOLLO',
    status: 'EMAIL_SENT',
    qualificationStatus: 'QUALIFIED',
    qualificationScore: 88,
    qualificationReason: 'Decision maker leading pilgrimage packages and wholesale agent distribution.',
    createdAt: '2026-09-13T10:00:00Z',
    updatedAt: '2026-09-14T09:30:00Z',
  },
  {
    prospectId: 'prospect-zuber-ahmed',
    campaignId: 'camp-indian-umrah-operators',
    apolloPersonId: 'ap_person_7718290',
    firstName: 'Zuber',
    lastName: 'Ahmed',
    email: 'zuber@deccanholidays.co.in',
    phone: '+91 94480 88990',
    jobTitle: 'Owner',
    companyName: 'Deccan Pilgrimage Services',
    industry: 'Tour Operator',
    companySize: '5-10 employees',
    location: 'Hyderabad, India',
    source: 'APOLLO',
    status: 'PROSPECTED',
    qualificationStatus: 'QUALIFIED',
    qualificationScore: 84,
    qualificationReason: 'Proprietor organizing Umrah departures for South Indian pilgrims.',
    createdAt: '2026-09-14T11:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
  },
];

// Initial Contacts
export const INITIAL_CONTACTS: Contact[] = [
  {
    contactId: 'contact-rahul-sharma',
    firstName: 'Rahul',
    lastName: 'Sharma',
    email: 'rahul@abctravels.in',
    phone: '+91 98100 23456',
    companyName: 'ABC Travels',
    jobTitle: 'Founder',
    apolloPersonId: 'ap_person_9847120',
    createdAt: '2026-09-12T09:00:00Z',
    updatedAt: '2026-09-15T11:20:00Z',
    lastActivityAt: '2026-09-15T11:20:00Z',
  },
  {
    contactId: 'contact-farhan-malik',
    firstName: 'Farhan',
    lastName: 'Malik',
    email: 'farhan@malikpilgrimages.co.uk',
    phone: '+44 7911 123456',
    companyName: 'Malik Pilgrimages UK',
    jobTitle: 'Managing Partner',
    whatsappUserId: '447911123456',
    createdAt: '2026-09-14T14:00:00Z',
    updatedAt: '2026-09-15T10:45:00Z',
    lastActivityAt: '2026-09-15T10:45:00Z',
  },
  {
    contactId: 'contact-amira-sayed',
    firstName: 'Amira',
    lastName: 'Sayed',
    email: 'amira@andalusholidays.ae',
    phone: '+971 50 987 6543',
    companyName: 'Andalus Holidays Dubai',
    jobTitle: 'Operations Lead',
    instagramUserId: 'andalus_holidays_dxb',
    createdAt: '2026-09-15T08:30:00Z',
    updatedAt: '2026-09-15T09:15:00Z',
    lastActivityAt: '2026-09-15T09:15:00Z',
  },
];

// Initial Leads
export const INITIAL_LEADS: Lead[] = [
  {
    leadId: 'lead-rahul-sharma',
    contactId: 'contact-rahul-sharma',
    source: 'APOLLO',
    leadType: 'OUTBOUND',
    status: 'QUALIFIED',
    leadScore: 89,
    intent: 'HIGH',
    buyingStage: 'CONSIDERATION',
    serviceInterest: 'B2B Sub-Agent Portal & Dynamic Costing',
    requirements: ['B2B Sub-Agent Portal', 'Real-time room costing', 'White-label PDF vouchers'],
    budget: 'Growth Plan or Custom ($500+/mo)',
    timeline: 'Within 3 weeks for upcoming season',
    aiSummary: 'Founder of ABC Travels engaged via cold email. Asked about software capabilities and confirmed high interest in B2B agent support.',
    aiRecommendation: 'Schedule product walkthrough focusing on Sub-Agent Credit Wallets and Invoicing.',
    campaignId: 'camp-indian-umrah-operators',
    createdAt: '2026-09-12T09:00:00Z',
    updatedAt: '2026-09-15T11:20:00Z',
    lastActivityAt: '2026-09-15T11:20:00Z',
  },
  {
    leadId: 'lead-farhan-malik',
    contactId: 'contact-farhan-malik',
    source: 'WHATSAPP',
    leadType: 'INBOUND',
    status: 'ENGAGED',
    leadScore: 82,
    intent: 'HIGH',
    buyingStage: 'CONSIDERATION',
    serviceInterest: 'FIT Customized Packages & Haramain Train Booking',
    requirements: ['Customized itineraries', 'Multi-currency (GBP/SAR)', 'Saudi eVisa tracking'],
    timeline: 'Immediate implementation',
    aiSummary: 'UK pilgrimage operator connected via WhatsApp asking for dynamic package builder capabilities.',
    aiRecommendation: 'Provide sample PDF itinerary export and Growth Plan pricing.',
    createdAt: '2026-09-14T14:00:00Z',
    updatedAt: '2026-09-15T10:45:00Z',
    lastActivityAt: '2026-09-15T10:45:00Z',
  },
  {
    leadId: 'lead-amira-sayed',
    contactId: 'contact-amira-sayed',
    source: 'INSTAGRAM',
    leadType: 'INBOUND',
    status: 'NEW',
    leadScore: 71,
    intent: 'MEDIUM',
    buyingStage: 'AWARENESS',
    serviceInterest: 'Umrah360 Overview & Hotel Contracts',
    requirements: ['Makkah hotel rates', 'Group booking management'],
    aiSummary: 'Inquired through Instagram DM regarding offline hotel allotments management.',
    aiRecommendation: 'Qualify team size and share overview brochure.',
    createdAt: '2026-09-15T08:30:00Z',
    updatedAt: '2026-09-15T09:15:00Z',
    lastActivityAt: '2026-09-15T09:15:00Z',
  },
];

// Initial Conversations
export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    conversationId: 'conv-rahul-sharma',
    contactId: 'contact-rahul-sharma',
    leadId: 'lead-rahul-sharma',
    channel: 'EMAIL',
    direction: 'OUTBOUND',
    campaignId: 'camp-indian-umrah-operators',
    status: 'ACTIVE',
    aiEnabled: true,
    humanHandoff: false,
    managementMode: 'AI',
    isRead: true,
    unread: false,
    unreadCount: 0,
    emailThreadId: 'thread-rahul-sharma',
    gmailThreadId: 'thread-rahul-sharma',
    conversationSummary: 'Cold email sent regarding Umrah360. Rahul replied asking for software details and confirmed B2B requirements.',
    memory: {
      customerFacts: ['Runs ABC Travels in New Delhi', 'Distributes packages via sub-agents across North India'],
      requirements: ['B2B Sub-Agent Portal', 'Dynamic margin costing'],
      questionsAsked: ['What does the software do?', 'Does it support B2B?'],
      questionsAnswered: ['Umrah360 platform overview', 'B2B portal and white-label vouchers'],
      questionsPending: [],
      objections: [],
      buyingStage: 'CONSIDERATION',
      nextAction: 'Answer pricing or book live demo',
    },
    startedAt: '2026-09-12T10:20:00Z',
    lastMessageAt: '2026-09-13T11:12:00Z',
    lastMessageText: 'Yes, Umrah360 provides a complete white-label B2B Sub-Agent Portal with custom markups and credit limits.',
    createdAt: '2026-09-12T10:20:00Z',
    updatedAt: '2026-09-13T11:12:00Z',
  },
  {
    conversationId: 'conv-rahul-whatsapp',
    contactId: 'contact-rahul-sharma',
    leadId: 'lead-rahul-sharma',
    channel: 'WHATSAPP',
    direction: 'INBOUND',
    status: 'ACTIVE',
    aiEnabled: true,
    humanHandoff: false,
    managementMode: 'AI',
    isRead: true,
    unread: false,
    unreadCount: 0,
    conversationSummary: 'Rahul reached out on WhatsApp inquiring about automated WhatsApp voucher dispatch to sub-agents.',
    memory: {
      customerFacts: ['Preferred mobile communication channel', 'Sub-agents actively demand WhatsApp vouchers'],
      requirements: ['WhatsApp PDF dispatch', 'Real-time booking alerts'],
      questionsAsked: ['Can we also do WhatsApp booking vouchers for our sub-agents?'],
      questionsAnswered: ['Yes, automatic WhatsApp dispatch on confirmed voucher generation.'],
      questionsPending: [],
      objections: [],
      buyingStage: 'CONSIDERATION',
    },
    startedAt: '2026-09-14T09:15:00Z',
    lastMessageAt: '2026-09-14T09:18:00Z',
    lastMessageText: 'Yes, confirmed B2B bookings trigger instant PDF vouchers and payment receipts directly to sub-agent WhatsApp numbers.',
    createdAt: '2026-09-14T09:15:00Z',
    updatedAt: '2026-09-14T09:18:00Z',
  },
  {
    conversationId: 'conv-rahul-linkedin',
    contactId: 'contact-rahul-sharma',
    leadId: 'lead-rahul-sharma',
    channel: 'LINKEDIN',
    direction: 'OUTBOUND',
    status: 'ACTIVE',
    aiEnabled: false,
    humanHandoff: false,
    managementMode: 'HUMAN',
    isRead: true,
    unread: false,
    unreadCount: 0,
    conversationSummary: 'LinkedIn executive message regarding Umrah360 travel tech innovations.',
    startedAt: '2026-09-11T16:00:00Z',
    lastMessageAt: '2026-09-11T16:00:00Z',
    lastMessageText: 'Great connecting with you Rahul. Following up regarding digital transformation for Umrah group operators.',
    createdAt: '2026-09-11T16:00:00Z',
    updatedAt: '2026-09-11T16:00:00Z',
  },
  {
    conversationId: 'conv-farhan-malik',
    contactId: 'contact-farhan-malik',
    leadId: 'lead-farhan-malik',
    channel: 'WHATSAPP',
    direction: 'INBOUND',
    status: 'ACTIVE',
    aiEnabled: true,
    humanHandoff: false,
    managementMode: 'AI',
    isRead: true,
    unread: false,
    unreadCount: 0,
    conversationSummary: 'Farhan from London inquired on WhatsApp regarding FIT itinerary generation and multi-currency GBP/SAR invoices.',
    memory: {
      customerFacts: ['London-based boutique Umrah agency', 'Needs GBP billing with Saudi Riyal hotel cost tracking'],
      requirements: ['Dynamic package builder', 'Multi-currency invoicing'],
      questionsAsked: ['Hi, I want to know about Umrah360', 'Does it calculate multi-currency exchange buffers?'],
      questionsAnswered: ['Platform overview', 'Live forex and tax compliance'],
      questionsPending: [],
      objections: [],
      buyingStage: 'CONSIDERATION',
      nextAction: 'Offer 1-on-1 walkthrough',
    },
    startedAt: '2026-09-14T14:10:00Z',
    lastMessageAt: '2026-09-15T10:45:00Z',
    lastMessageText: 'Yes, our live Forex engine automatically converts SAR costs to GBP with customizable hedge buffers.',
    createdAt: '2026-09-14T14:10:00Z',
    updatedAt: '2026-09-15T10:45:00Z',
  },
  {
    conversationId: 'conv-farhan-email',
    contactId: 'contact-farhan-malik',
    leadId: 'lead-farhan-malik',
    channel: 'EMAIL',
    direction: 'INBOUND',
    status: 'ACTIVE',
    aiEnabled: true,
    humanHandoff: false,
    managementMode: 'AI',
    isRead: true,
    unread: false,
    unreadCount: 0,
    emailThreadId: 'thread-farhan-email',
    gmailThreadId: 'thread-farhan-email',
    conversationSummary: 'Formal inquiry email regarding UK ATOL compliance and Haramain rail booking API.',
    startedAt: '2026-09-15T07:30:00Z',
    lastMessageAt: '2026-09-15T08:05:00Z',
    lastMessageText: 'Thank you for the detailed breakdown on ATOL-compliant client account invoicing.',
    createdAt: '2026-09-15T07:30:00Z',
    updatedAt: '2026-09-15T08:05:00Z',
  },
  {
    conversationId: 'conv-amira-sayed',
    contactId: 'contact-amira-sayed',
    leadId: 'lead-amira-sayed',
    channel: 'INSTAGRAM',
    direction: 'INBOUND',
    status: 'ACTIVE',
    aiEnabled: true,
    humanHandoff: false,
    managementMode: 'AI',
    isRead: true,
    unread: false,
    unreadCount: 0,
    conversationSummary: 'Amira asked if Umrah360 supports Makkah Clock Tower contract allotments.',
    memory: {
      customerFacts: ['Dubai agency coordinator'],
      requirements: ['Hotel allotment management'],
      questionsAsked: ['Can we load our existing contracted hotel allotments?'],
      questionsAnswered: ['Yes, offline custom inventory contracts are fully supported.'],
      questionsPending: [],
      objections: [],
      buyingStage: 'AWARENESS',
    },
    startedAt: '2026-09-15T08:30:00Z',
    lastMessageAt: '2026-09-15T09:15:00Z',
    lastMessageText: 'Yes! Umrah360 allows loading custom negotiated hotel blocks with blackout dates alongside online inventory.',
    createdAt: '2026-09-15T08:30:00Z',
    updatedAt: '2026-09-15T09:15:00Z',
  },
  {
    conversationId: 'conv-amira-whatsapp',
    contactId: 'contact-amira-sayed',
    leadId: 'lead-amira-sayed',
    channel: 'WHATSAPP',
    direction: 'INBOUND',
    status: 'ACTIVE',
    aiEnabled: true,
    humanHandoff: false,
    managementMode: 'AI',
    isRead: true,
    unread: false,
    unreadCount: 0,
    conversationSummary: 'Amira followed up on WhatsApp asking for demo link.',
    startedAt: '2026-09-15T11:00:00Z',
    lastMessageAt: '2026-09-15T11:02:00Z',
    lastMessageText: 'Shared demo link for Dubai operations team.',
    createdAt: '2026-09-15T11:00:00Z',
    updatedAt: '2026-09-15T11:02:00Z',
  },
];

// Initial Messages for Section 17 & 19 (Rahul Sharma thread)
export const INITIAL_MESSAGES: Message[] = [
  {
    messageId: 'msg-rahul-1',
    conversationId: 'conv-rahul-sharma',
    channel: 'EMAIL',
    senderType: 'AGENT',
    senderName: 'Umrah360 Growth Team',
    senderEmail: 'sales@umrah360.in',
    direction: 'OUTBOUND',
    gmailMessageId: '<cold-msg-001@umrah360.in>',
    gmailThreadId: 'thread-rahul-sharma',
    sentAt: '2026-09-12T10:20:00Z',
    receivedAt: '2026-09-12T10:20:00Z',
    createdAt: '2026-09-12T10:20:00Z',
    text: `Hi Rahul,\n\nWe work with Umrah operators across India to automate their dynamic package costing, Makkah/Madinah room allotments, and sub-agent B2B voucher distribution.\n\nMost operators we speak with were spending 15+ hours weekly updating manual spreadsheets and WhatsApp groups for agent pricing. Umrah360 gives your agency an automated B2B portal with live supplier costs and compliant invoicing.\n\nWould you be open to exploring how this could streamline your upcoming season?\n\nRegards,\nUmrah360 Growth Team`,
    timestamp: '2026-09-12T10:20:00Z',
    emailMeta: {
      subject: 'Umrah360 for ABC Travels - Automate B2B Packages & Visa Operations',
      from: 'sales@umrah360.in',
      to: 'rahul@abctravels.in',
      messageId: '<cold-msg-001@umrah360.in>',
    },
  },
  {
    messageId: 'msg-rahul-2',
    conversationId: 'conv-rahul-sharma',
    channel: 'EMAIL',
    senderType: 'PROSPECT',
    senderName: 'Rahul Sharma',
    senderEmail: 'rahul@abctravels.in',
    direction: 'INBOUND',
    aiReplied: true,
    repliedAt: '2026-09-12T14:18:00Z',
    repliedByMessageId: '<ai-reply-001@umrah360.in>',
    gmailMessageId: '<rahul-reply-001@abctravels.in>',
    gmailThreadId: 'thread-rahul-sharma',
    sentAt: '2026-09-12T14:15:00Z',
    receivedAt: '2026-09-12T14:15:00Z',
    createdAt: '2026-09-12T14:15:00Z',
    text: `Hi, can you explain what the software does? We currently manage packages across Delhi and Lucknow.`,
    timestamp: '2026-09-12T14:15:00Z',
    emailMeta: {
      subject: 'Re: Umrah360 for ABC Travels - Automate B2B Packages & Visa Operations',
      from: 'rahul@abctravels.in',
      to: 'sales@umrah360.in',
      messageId: '<rahul-reply-001@abctravels.in>',
      inReplyTo: '<cold-msg-001@umrah360.in>',
      references: ['<cold-msg-001@umrah360.in>'],
    },
  },
  {
    messageId: 'msg-rahul-3',
    conversationId: 'conv-rahul-sharma',
    channel: 'EMAIL',
    senderType: 'AI',
    senderName: 'Umrah360 AI',
    direction: 'OUTBOUND',
    gmailMessageId: '<ai-reply-001@umrah360.in>',
    gmailThreadId: 'thread-rahul-sharma',
    sentAt: '2026-09-12T14:18:00Z',
    receivedAt: '2026-09-12T14:18:00Z',
    createdAt: '2026-09-12T14:18:00Z',
    text: `Hi Rahul,\n\nUmrah360 is an all-in-one cloud ERP and CRM software purpose-built for Hajj and Umrah tour operators. It unifies lead management, FIT (Free Independent Traveler) and group package creation, dynamic costing, multi-currency invoicing, Saudi visa tracking, hotel & transport allotments, and sub-agent B2B networks into a single cohesive interface.\n\nAre you currently handling your operations through spreadsheets or looking to upgrade from another system?\n\nRegards,\nUmrah360 Team`,
    timestamp: '2026-09-12T14:18:00Z',
    aiProcessed: true,
    aiGenerated: true,
    confidence: 0.96,
    knowledgeSources: ['Umrah360 Platform Architecture & Capabilities Overview'],
    emailMeta: {
      subject: 'Re: Umrah360 for ABC Travels - Automate B2B Packages & Visa Operations',
      from: 'sales@umrah360.in',
      to: 'rahul@abctravels.in',
      messageId: '<ai-reply-001@umrah360.in>',
      inReplyTo: '<rahul-reply-001@abctravels.in>',
      references: ['<cold-msg-001@umrah360.in>', '<rahul-reply-001@abctravels.in>'],
    },
  },
  {
    messageId: 'msg-rahul-4',
    conversationId: 'conv-rahul-sharma',
    channel: 'EMAIL',
    senderType: 'PROSPECT',
    senderName: 'Rahul Sharma',
    senderEmail: 'rahul@abctravels.in',
    direction: 'INBOUND',
    aiReplied: true,
    repliedAt: '2026-09-13T11:12:00Z',
    repliedByMessageId: '<ai-reply-002@umrah360.in>',
    gmailMessageId: '<rahul-reply-002@abctravels.in>',
    gmailThreadId: 'thread-rahul-sharma',
    sentAt: '2026-09-13T11:10:00Z',
    receivedAt: '2026-09-13T11:10:00Z',
    createdAt: '2026-09-13T11:10:00Z',
    text: `Does it support B2B agents? We have around 40 local sub-agents who book packages through us.`,
    timestamp: '2026-09-13T11:10:00Z',
    emailMeta: {
      subject: 'Re: Umrah360 for ABC Travels - Automate B2B Packages & Visa Operations',
      from: 'rahul@abctravels.in',
      to: 'sales@umrah360.in',
      messageId: '<rahul-reply-002@abctravels.in>',
      inReplyTo: '<ai-reply-001@umrah360.in>',
      references: ['<cold-msg-001@umrah360.in>', '<rahul-reply-001@abctravels.in>', '<ai-reply-001@umrah360.in>'],
    },
  },
  {
    messageId: 'msg-rahul-5',
    conversationId: 'conv-rahul-sharma',
    channel: 'EMAIL',
    senderType: 'AI',
    senderName: 'Umrah360 AI',
    direction: 'OUTBOUND',
    gmailMessageId: '<ai-reply-002@umrah360.in>',
    gmailThreadId: 'thread-rahul-sharma',
    sentAt: '2026-09-13T11:12:00Z',
    receivedAt: '2026-09-13T11:12:00Z',
    createdAt: '2026-09-13T11:12:00Z',
    text: `Hi Rahul,\n\nYes! Umrah360 includes a dedicated white-label B2B Sub-Agent Portal built specifically for tour operators distributing packages to external agents. It allows you to:\n• Set custom markup & commission tiers per sub-agent category\n• Manage live credit limits, wallets, and ledger deposits\n• Allow sub-agents to search contracted inventory and instantly issue branded PDF vouchers with their own agency logo\n\nWould you like to see how sub-agent allotments and credit limits are configured in a quick demo?\n\nRegards,\nUmrah360 Team`,
    timestamp: '2026-09-13T11:12:00Z',
    aiProcessed: true,
    aiGenerated: true,
    confidence: 0.98,
    knowledgeSources: ['B2B Sub-Agent Portal & Reseller Distribution Engine'],
    emailMeta: {
      subject: 'Re: Umrah360 for ABC Travels - Automate B2B Packages & Visa Operations',
      from: 'sales@umrah360.in',
      to: 'rahul@abctravels.in',
      messageId: '<ai-reply-002@umrah360.in>',
      inReplyTo: '<rahul-reply-002@abctravels.in>',
      references: ['<cold-msg-001@umrah360.in>', '<rahul-reply-001@abctravels.in>', '<ai-reply-001@umrah360.in>', '<rahul-reply-002@abctravels.in>'],
    },
  },
  // Rahul Sharma - WhatsApp Conversation Messages
  {
    messageId: 'msg-rahul-wa-1',
    conversationId: 'conv-rahul-whatsapp',
    channel: 'WHATSAPP',
    senderType: 'CUSTOMER',
    senderName: 'Rahul Sharma',
    direction: 'INBOUND',
    sentAt: '2026-09-14T09:15:00Z',
    receivedAt: '2026-09-14T09:15:00Z',
    createdAt: '2026-09-14T09:15:00Z',
    text: 'Hi! Rahul here from ABC Travels. Just sent our team a link to Umrah360. Can we also do WhatsApp booking vouchers for our sub-agents?',
    timestamp: '2026-09-14T09:15:00Z',
  },
  {
    messageId: 'msg-rahul-wa-2',
    conversationId: 'conv-rahul-whatsapp',
    channel: 'WHATSAPP',
    senderType: 'AI',
    senderName: 'Umrah360 AI',
    direction: 'OUTBOUND',
    sentAt: '2026-09-14T09:18:00Z',
    receivedAt: '2026-09-14T09:18:00Z',
    createdAt: '2026-09-14T09:18:00Z',
    text: 'Assalamu Alaikum Rahul! Yes, Umrah360 features automated WhatsApp dispatch where confirmed B2B bookings trigger instant PDF vouchers and payment receipts directly to sub-agent WhatsApp numbers with your agency branding.',
    timestamp: '2026-09-14T09:18:00Z',
    aiProcessed: true,
    aiGenerated: true,
    confidence: 0.97,
    knowledgeSources: ['B2B Sub-Agent Portal & Reseller Distribution Engine'],
  },
  // Rahul Sharma - LinkedIn Conversation Messages
  {
    messageId: 'msg-rahul-li-1',
    conversationId: 'conv-rahul-linkedin',
    channel: 'LINKEDIN',
    senderType: 'AGENT',
    senderName: 'Umrah360 Growth Team',
    direction: 'OUTBOUND',
    sentAt: '2026-09-11T16:00:00Z',
    receivedAt: '2026-09-11T16:00:00Z',
    createdAt: '2026-09-11T16:00:00Z',
    text: 'Great connecting with you Rahul. Following up regarding digital transformation for Umrah group operators.',
    timestamp: '2026-09-11T16:00:00Z',
  },
  // Farhan Malik - WhatsApp Conversation Messages
  {
    messageId: 'msg-farhan-wa-1',
    conversationId: 'conv-farhan-malik',
    channel: 'WHATSAPP',
    senderType: 'CUSTOMER',
    senderName: 'Farhan Malik',
    direction: 'INBOUND',
    sentAt: '2026-09-14T14:10:00Z',
    receivedAt: '2026-09-14T14:10:00Z',
    createdAt: '2026-09-14T14:10:00Z',
    text: 'Hi, I want to know about Umrah360 for my UK travel agency.',
    timestamp: '2026-09-14T14:10:00Z',
  },
  {
    messageId: 'msg-farhan-wa-2',
    conversationId: 'conv-farhan-malik',
    channel: 'WHATSAPP',
    senderType: 'AI',
    senderName: 'Umrah360 AI',
    direction: 'OUTBOUND',
    sentAt: '2026-09-14T14:12:00Z',
    receivedAt: '2026-09-14T14:12:00Z',
    createdAt: '2026-09-14T14:12:00Z',
    text: 'Hello Farhan! Umrah360 is an all-in-one cloud ERP and CRM platform purpose-built for Hajj and Umrah tour operators. It streamlines dynamic package generation, Makkah/Madinah room allotments, multi-currency invoicing, and B2B agent networks. Are you looking to upgrade from spreadsheets?',
    timestamp: '2026-09-14T14:12:00Z',
    aiProcessed: true,
    aiGenerated: true,
    confidence: 0.95,
    knowledgeSources: ['Umrah360 Platform Architecture & Capabilities Overview'],
  },
  {
    messageId: 'msg-farhan-wa-3',
    conversationId: 'conv-farhan-malik',
    channel: 'WHATSAPP',
    senderType: 'CUSTOMER',
    senderName: 'Farhan Malik',
    direction: 'INBOUND',
    sentAt: '2026-09-15T10:42:00Z',
    receivedAt: '2026-09-15T10:42:00Z',
    createdAt: '2026-09-15T10:42:00Z',
    text: 'Can we calculate multi-currency exchange buffers between GBP and SAR?',
    timestamp: '2026-09-15T10:42:00Z',
  },
  {
    messageId: 'msg-farhan-wa-4',
    conversationId: 'conv-farhan-malik',
    channel: 'WHATSAPP',
    senderType: 'AI',
    senderName: 'Umrah360 AI',
    direction: 'OUTBOUND',
    sentAt: '2026-09-15T10:45:00Z',
    receivedAt: '2026-09-15T10:45:00Z',
    createdAt: '2026-09-15T10:45:00Z',
    text: 'Yes! Our live Forex engine automatically converts SAR costs to GBP with customizable hedge buffers and generates compliant VAT invoices. Would you like to see a sample itinerary?',
    timestamp: '2026-09-15T10:45:00Z',
    aiProcessed: true,
    aiGenerated: true,
    confidence: 0.98,
    knowledgeSources: ['Dynamic Package Costing & Multi-Currency Architecture'],
  },
  // Farhan Malik - Email Conversation Messages
  {
    messageId: 'msg-farhan-em-1',
    conversationId: 'conv-farhan-email',
    channel: 'EMAIL',
    senderType: 'CUSTOMER',
    senderName: 'Farhan Malik',
    senderEmail: 'farhan@malikpilgrimages.co.uk',
    direction: 'INBOUND',
    aiReplied: true,
    repliedAt: '2026-09-15T08:05:00Z',
    repliedByMessageId: '<concierge-reply-001@umrah360.in>',
    gmailMessageId: '<farhan-inquiry-001@malikpilgrimages.co.uk>',
    gmailThreadId: 'thread-farhan-email',
    sentAt: '2026-09-15T07:30:00Z',
    receivedAt: '2026-09-15T07:30:00Z',
    createdAt: '2026-09-15T07:30:00Z',
    text: 'Hi Team,\n\nWe need to confirm how Umrah360 handles ATOL client account compliance and group seat bookings on the Haramain High Speed train. Could you share technical documentation on that?\n\nRegards,\nFarhan Malik\nMalik Pilgrimages UK',
    timestamp: '2026-09-15T07:30:00Z',
    emailMeta: {
      subject: 'Inquiry: ATOL Compliance & Haramain Rail Booking API',
      from: 'farhan@malikpilgrimages.co.uk',
      to: 'sales@umrah360.in',
      messageId: '<farhan-inquiry-001@malikpilgrimages.co.uk>',
    },
  },
  {
    messageId: 'msg-farhan-em-2',
    conversationId: 'conv-farhan-email',
    channel: 'EMAIL',
    senderType: 'AGENT',
    senderName: 'Umrah360 Concierge',
    senderEmail: 'sales@umrah360.in',
    direction: 'OUTBOUND',
    gmailMessageId: '<concierge-reply-001@umrah360.in>',
    gmailThreadId: 'thread-farhan-email',
    sentAt: '2026-09-15T08:05:00Z',
    receivedAt: '2026-09-15T08:05:00Z',
    createdAt: '2026-09-15T08:05:00Z',
    text: 'Hi Farhan,\n\nOur platform maintains ring-fenced trust accounting fields compatible with UK ATOL guidelines and integrates direct voucher exports for Haramain group bookings. We have attached the technical specifications.\n\nBest regards,\nUmrah360 Team',
    timestamp: '2026-09-15T08:05:00Z',
    emailMeta: {
      subject: 'Re: Inquiry: ATOL Compliance & Haramain Rail Booking API',
      from: 'sales@umrah360.in',
      to: 'farhan@malikpilgrimages.co.uk',
      messageId: '<concierge-reply-001@umrah360.in>',
      inReplyTo: '<farhan-inquiry-001@malikpilgrimages.co.uk>',
      references: ['<farhan-inquiry-001@malikpilgrimages.co.uk>'],
    },
  },
  // Amira Sayed - Instagram DM
  {
    messageId: 'msg-amira-ig-1',
    conversationId: 'conv-amira-sayed',
    channel: 'INSTAGRAM',
    senderType: 'CUSTOMER',
    senderName: 'Amira Sayed',
    direction: 'INBOUND',
    sentAt: '2026-09-15T08:30:00Z',
    receivedAt: '2026-09-15T08:30:00Z',
    createdAt: '2026-09-15T08:30:00Z',
    text: 'Can we load our existing contracted hotel allotments from Makkah Clock Tower?',
    timestamp: '2026-09-15T08:30:00Z',
  },
  {
    messageId: 'msg-amira-ig-2',
    conversationId: 'conv-amira-sayed',
    channel: 'INSTAGRAM',
    senderType: 'AI',
    senderName: 'Umrah360 AI',
    direction: 'OUTBOUND',
    sentAt: '2026-09-15T09:15:00Z',
    receivedAt: '2026-09-15T09:15:00Z',
    createdAt: '2026-09-15T09:15:00Z',
    text: 'Yes! Umrah360 allows loading custom negotiated hotel blocks with blackout dates alongside online inventory.',
    timestamp: '2026-09-15T09:15:00Z',
    aiProcessed: true,
    aiGenerated: true,
    confidence: 0.94,
    knowledgeSources: ['Umrah360 Platform Architecture & Capabilities Overview'],
  },
];

// Initial Email Thread
export const INITIAL_EMAIL_THREADS: EmailThread[] = [
  {
    emailThreadId: 'thread-rahul-sharma',
    conversationId: 'conv-rahul-sharma',
    subject: 'Umrah360 for ABC Travels - Automate B2B Packages & Visa Operations',
    participants: ['sales@umrah360.in', 'rahul@abctravels.in'],
    contactId: 'contact-rahul-sharma',
    leadId: 'lead-rahul-sharma',
    campaignId: 'camp-indian-umrah-operators',
    firstMessageAt: '2026-09-12T10:20:00Z',
    lastMessageAt: '2026-09-13T11:12:00Z',
    status: 'OPEN',
    createdAt: '2026-09-12T10:20:00Z',
    updatedAt: '2026-09-13T11:12:00Z',
  },
];

// Initial Activities
export const INITIAL_ACTIVITIES: LeadActivity[] = [
  {
    activityId: 'act-1',
    leadId: 'lead-rahul-sharma',
    contactId: 'contact-rahul-sharma',
    type: 'PROSPECT_ADDED',
    title: 'Prospect Discovered via Apollo',
    description: 'Rahul Sharma (Founder at ABC Travels) discovered via Indian Umrah Operators campaign search.',
    timestamp: '2026-09-12T09:00:00Z',
  },
  {
    activityId: 'act-2',
    leadId: 'lead-rahul-sharma',
    contactId: 'contact-rahul-sharma',
    type: 'COLD_EMAIL_SENT',
    title: 'Cold Outreach Email Dispatched',
    description: 'Sent Introduction to Umrah360 personalized with companyName: ABC Travels.',
    timestamp: '2026-09-12T10:20:00Z',
  },
  {
    activityId: 'act-3',
    leadId: 'lead-rahul-sharma',
    contactId: 'contact-rahul-sharma',
    type: 'PROSPECT_REPLIED',
    title: 'Prospect Replied',
    description: 'Rahul replied asking for software capabilities in Delhi & Lucknow.',
    timestamp: '2026-09-12T14:15:00Z',
  },
  {
    activityId: 'act-4',
    leadId: 'lead-rahul-sharma',
    contactId: 'contact-rahul-sharma',
    type: 'AI_REPLIED',
    title: 'AI Auto-Reply Sent',
    description: 'AI responded in same thread with platform overview from Knowledge Base (Confidence: 96%).',
    timestamp: '2026-09-12T14:18:00Z',
  },
  {
    activityId: 'act-5',
    leadId: 'lead-rahul-sharma',
    contactId: 'contact-rahul-sharma',
    type: 'PROSPECT_REPLIED',
    title: 'Inquired About B2B Agents',
    description: 'Rahul asked about 40 local sub-agents booking packages.',
    timestamp: '2026-09-13T11:10:00Z',
  },
  {
    activityId: 'act-6',
    leadId: 'lead-rahul-sharma',
    contactId: 'contact-rahul-sharma',
    type: 'AI_REPLIED',
    title: 'AI Explained B2B Capabilities',
    description: 'AI confirmed B2B Sub-Agent portal, custom markup, and white-label vouchers (Confidence: 98%).',
    timestamp: '2026-09-13T11:12:00Z',
  },
];

/**
 * Duplicate Detection Service (Section 9)
 * Checks email, phone, company + email, and Apollo person ID before creating any contact
 */
export function findDuplicateContact(
  candidate: { email?: string; phone?: string; companyName?: string; apolloPersonId?: string },
  existingContacts: Contact[]
): Contact | null {
  const targetEmail = candidate.email?.trim().toLowerCase();
  const targetPhone = candidate.phone?.replace(/[^\d]/g, '');
  const targetCompany = candidate.companyName?.trim().toLowerCase();

  for (const c of existingContacts) {
    // Check Apollo Person ID
    if (candidate.apolloPersonId && c.apolloPersonId === candidate.apolloPersonId) {
      return c;
    }
    // Check exact email
    if (targetEmail && c.email.toLowerCase() === targetEmail) {
      return c;
    }
    // Check phone
    if (targetPhone && c.phone && c.phone.replace(/[^\d]/g, '') === targetPhone) {
      return c;
    }
    // Check company + similar name
    if (targetCompany && c.companyName.toLowerCase() === targetCompany && targetEmail && c.email.toLowerCase().split('@')[1] === targetEmail.split('@')[1]) {
      return c;
    }
  }

  return null;
}
